### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [erikschreier/PaperColor-themes#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license or a screen shot.

Please add a screen shot so people can see what the theme will look like without having to install it.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one.

**Comment by erikschreier** [comment]
Thank you for your request, its a suprise someone realy is interested in this way, so thank you, Screenshot and License was added.

**Comment by unixorn** [comment]
Added to the list.
